### ISSUE TITLE
The "statement" argument is surrounded by quotes causing a syntax error

### ISSUE THREAD

**Issue by techfishio** [cloudposse/terraform-aws-iam-policy-document-aggregator#8]
```
$ terraform --version
Terraform v0.12.6
+ provider.aws v2.23.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

When using a module that uses this dependent module Terraform throws an error on `terraform init`:

```
$ terraform init

[snip]

There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that Terraform can determine which modules and providers need to be installed.

Error: Invalid argument name

  on .terraform/modules/kms_key.policy/main.tf line 24, in data "aws_iam_policy_document" "zero":
  24:   "statement"   = []

Argument names must not be quoted.
```

**Comment by techfishio** [comment]
The module isn't `0.12` compatible: https://github.com/cloudposse/terraform-root-modules#usage

**Comment by shaiss** [comment]
But that's for KMS. I'm using this module as part of the cloudposse IAM
role.

**Comment by techfishio** [comment]
@shaiss I ended up needing this as well, as a dependency of `terraform_aws_iam_role`. I upgraded it to `0.12` in a fork here: https://github.com/techfishio/terraform-aws-iam-policy-document-aggregator/tree/0.2.0

You should be able to use that if needed.
